### **NUMPY**

In [2]:
import numpy as np

Creating an array

In [5]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

Operations

In [6]:
a + 5

array([6, 7, 8])

In [7]:
a * 2

array([2, 4, 6])

In [8]:
a ** 2

array([1, 4, 9])

Accessing Data

In [12]:
a[0]


np.int64(1)

In [13]:
a[-1]


np.int64(3)

In [14]:
a[0:2]

array([1, 2])

### 2D Array

In [15]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

matrix[0,1]

np.int64(2)

In [16]:
matrix[:,1]

array([2, 5])

In [17]:
matrix[1,:]

array([4, 5, 6])

### SHAPE and DIMENSIONS

In [18]:
a.shape

(3,)

In [19]:
a.ndim #dimensions

1

### Aggregation Functions

In [20]:
np.sum(a)

np.int64(6)

In [21]:
np.mean(a)

np.float64(2.0)

In [22]:
np.min(a)

np.int64(1)

In [23]:
np.max(a)

np.int64(3)

In [24]:
np.std(a) # standard deviation (how spread the numbers are)

np.float64(0.816496580927726)

In [25]:
np.mean(matrix, axis=0)

array([2.5, 3.5, 4.5])

In [26]:
a = np.array([10, 20, 30, 40])

a > 20

array([False, False,  True,  True])

In [27]:
a[a > 20]

array([30, 40])

### Random numbers

In [28]:
np.random.rand(3)
np.random.randint(1, 10, 5)

array([8, 4, 9, 4, 8])